//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BowPad.rc
//
#define IDC_MYICON                      2
#define IDD_BOWPAD_DIALOG               102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDS_ERR_FILETOOBIG              104
#define IDS_NEW_TABTITLE                105
#define IDS_DOYOUWANTOSAVE              106
#define IDI_BOWPAD                      107
#define IDS_SAVE                        107
#define IDS_DONTSAVE                    108
#define IDC_BOWPAD                      109
#define IDS_CANCEL                      110
#define IDS_HASMODIFICATIONS            111
#define IDS_ENCODING_MAIN               112
#define IDS_ENCODING_CODEPAGES          113
#define IDS_HOWTOOPENURL                114
#define IDS_GOTOLINEINFO                115
#define IDS_OUTSIDEMODIFICATIONS        116
#define IDS_DOYOUWANTRELOADBUTDIRTY     117
#define IDS_DOYOUWANTTORELOAD           118
#define IDS_SAVELOSTOUTSIDEMODS         119
#define IDS_RELOAD                      120
#define IDS_RELOADLOSTMODS              121
#define IDS_NORELOAD                    122
#define IDS_OUTSIDEREMOVEDHEAD          123
#define IDS_OUTSIDEREMOVED              124
#define IDS_OUTSIDEREMOVEDKEEP          125
#define IDS_OUTSIDEREMOVEDCLOSE         126
#define IDS_UPDATEAVAILABLE_DOWNLOAD_INSTALL_BTN_TEXT 127
#define IDR_MAINFRAME                   128
#define IDS_UPDATEAVAILABLE_DOWNLOAD_BTN_TEXT 128
#define IDC_DRAG_TAB                    129
#define IDS_UPDATEAVAILABLE_DONT_DOWNLOAD_BTN_TEXT 129
#define IDC_DRAG_INTERDIT_TAB           130
#define IDS_UPDATEAVAILABLE_TASKDLG_TITLE 130
#define IDC_DRAG_OUT_TAB                131
#define IDS_UPDATEAVAILABLE_TASKDLG_HEADER 131
#define IDC_DRAG_PLUS_TAB               132
#define IDS_UPDATEAVAILABLE_TASKDLG_CHKBOX_TEXT 132
#define IDR_CLOSETAB                    133
#define IDS_UPDATEAVAILABLE_TASKDLG_FOOTER 133
#define IDR_CLOSETAB_HOVER              134
#define IDS_NOUPDATES                   134
#define IDR_CLOSETAB_INACT              135
#define IDS_LANGUAGE_AVAILABLE          135
#define IDR_CLOSETAB_PUSH               136
#define IDS_LANGUAGE_REMOTE             136
#define IDI_READONLY_ICON               137
#define IDS_LANGUAGE_FETCH              137
#define IDI_SAVED_ICON                  138
#define IDS_LANGUAGE_RESTART            138
#define IDI_UNSAVED_ICON                139
#define IDS_LANGUAGE_DOWNLOADFAILED     139
#define IDR_CONFIG1                     140
#define IDR_LEXSTYLES                   140
#define IDS_LANGUAGE_DOWNLOADOK         140
#define IDR_SHORTCUTS                   141
#define IDS_LANGUAGE_DOWNLOADFAILEDFILE 141
#define IDB_EMPTY                       142
#define IDS_CUSTOMCOMMANDSINFO          142
#define IDD_FINDREPLACEDLG              143
#define IDS_FINDRETRYWRAP               143
#define IDD_STYLECONFIGURATOR           144
#define IDS_FINDNOTFOUND                144
#define IDD_GOTOLINE                    145
#define IDS_ACCESS_ELEVATE              145
#define IDS_ACCESS_ASK_ELEVATE          146
#define IDR_DARKTHEME                   147
#define IDS_ELEVATEOPEN                 147
#define IDD_CHOSE                       148
#define IDS_DONTELEVATEOPEN             148
#define IDD_CUSTOMCOMMANDSDLG           149
#define IDS_ELEVATESAVE                 149
#define IDS_DONTELEVATESAVE             150
#define IDI_BOWPAD_ELEVATED             150
#define IDI_ICON1                       151
#define IDI_ELEVATED                    151
#define IDS_NOFUNCTIONSFOUND            151
#define IDR_CONFIG2                     152
#define IDR_BOWPADUIH                   152
#define IDS_FINDRESULT_HEADERFILE       152
#define IDS_FINDRESULT_HEADERLINE       153
#define IDD_DEFAULTENCODING             153
#define IDR_SCINTILLAH                  153
#define IDS_FINDRESULT_HEADERLINETEXT   154
#define IDD_PLUGINSCONFIGDLG            154
#define IDS_REGEXTOOLTIP                155
#define IDI_ICON2                       155
#define IDI_BOWPAD_DOC                  155
#define IDS_REGEX_OK                    156
#define IDD_SUMMARY                     156
#define IDS_REGEX_NOTOK                 157
#define IDC_DRAG_COPYFILE               157
#define IDS_FINDALL                     158
#define IDC_CURSOR2                     158
#define IDC_DRAG_MOVEFILE               158
#define IDS_FINDALLINTABS               159
#define IDS_REPLACEALL                  160
#define IDS_FILE_DOESNT_EXIST           161
#define IDS_FILE_ASK_TO_CREATE          162
#define IDS_FILE_CREATE                 163
#define IDS_FILE_CREATE_CANCEL          164
#define IDS_RELOADREALLY                165
#define IDS_DORELOAD                    166
#define IDS_DONTRELOAD                  167
#define IDS_REPLACEALLINSELECTION       168
#define IDS_FAILEDTOLOADFILE            169
#define IDS_COPYTITLE                   170
#define IDS_FILEDELETE_TITLE            171
#define IDS_FILEDELETE_ASK              172
#define IDS_FILEDELETE_DEL              173
#define IDS_FILEDELETE_CANCEL           174
#define IDS_REPLACEALLINTABS            175
#define IDS_STATUSTTDOCSIZE             176
#define IDS_STATUSTTCURPOS              177
#define IDS_STATUSTTEOF                 178
#define IDS_STATUSTTTYPING              179
#define IDS_STATUSTTTYPINGOVL           180
#define IDS_STATUSTTTYPINGINS           181
#define IDS_STATUSTTTABS                182
#define IDS_FILEISREADONLY              183
#define IDS_FILEMAKEWRITABLEASK         184
#define IDS_EDITFILE                    185
#define IDS_KEEPREADONLY                186
#define IDS_FAILEDTOSAVEFILE            186
#define IDS_ELEVATED                    187
#define IDS_NO_PLUGINS                  188
#define IDS_PLUGINLIST_NAME             189
#define IDS_PLUGINLIST_VERSION          190
#define IDS_PLUGINLIST_INSTVERSION      191
#define IDS_PLUGINS_RESTARTREQUIRED     192
#define IDS_PLUGINS_INSTALLFAILED       193
#define IDS_CORRESPONDING_FILES         194
#define IDS_USER_INCLUDES               195
#define IDS_SYSTEM_INCLUDES             196
#define IDS_NO_FILES_FOUND              197
#define IDS_FINDRESULT_COUNT            198
#define IDS_FINDRESULT_COUNTALL         199
#define IDS_STATUSSELECTION             200
#define IDS_CREATE_CORRESPONDING_FILE   201
#define IDS_CREATE_CORRESPONDING_FILE_CATEGORY 202
#define IDD_SORTDLG                     203
#define IDS_SUMMARY                     203
#define IDS_ASCENDING                   204
#define IDS_DESCENDING                  205
#define IDS_STATUSTTTABSPACES           206
#define IDS_STATUSTTENCODING            207
#define IDS_STATUSZOOM                  208
#define IDS_ENCODING_MRU                209
#define IDS_FINDALLINDIR                210
#define IDS_SEARCHING_FILE              211
#define IDS_DOITFORALLFILES             212
#define IDS_SPELLCHECK_CORRECT          213
#define IDS_SPELLCHECK_IGNORE           214
#define IDS_SPELLCHECK_NOSUGGESTIONS    215
#define IDS_SPELLCHECK_IGNORESESSION    216
#define IDS_SPELLCHECK_ADDTODICTIONARY  217
#define IDS_FILE_DROP                   218
#define IDS_FILE_DROP_COPY              219
#define IDS_FILE_DROP_MOVE              220
#define IDS_FILE_DROP_DOCOPY            221
#define IDS_FILE_DROP_DOMOVE            222
#define IDS_FILE_DROP_CANCEL            223
#define IDS_REPLACEDCOUNT               224
#define IDS_FINDFILES                   225
#define IDS_NOSEARCHFOLDER              226
#define IDS_SEARCHFOLDERNOTFOUND        227
#define IDS_TT_SETSEARCHFOLDERTOPARENT  228
#define IDS_TT_SETSEARCHFOLDERCURRENT   229
#define IDS_TT_SETSEARCHFOLDER          230
#define IDS_TT_FINDPREVIOUS             231
#define IDS_PLEASEWAIT                  232
#define IDS_NOFUNCTIONFINDORREPLACE     233
#define IDS_NOMORETOREPLACE             234
#define IDS_SEARCHFILESLABEL            235
#define IDS_SESSIONLOADING_TITLE        235
#define IDS_SEARCHFOLDERLABEL           236
#define IDS_FILELOADING_TITLE           236
#define IDS_NEWCORRESPONDINGFILES       237
#define IDD_CORRESPONDINGFILEDLG        238
#define IDS_SEARCHING_FILE_MAX          238
#define IDS_CORRESPONDING_FILE_ERR_FILENAMEFIRST 239
#define IDI_CAPSLOCK                    239
#define IDS_CORRESPONDING_FILE_ERR_FILENAMESECOND 240
#define IDI_LEXER                       240
#define IDS_CORRESPONDING_FILE_ERR_FILENAMESMUSTBEDIFFERENT 241
#define IDI_ZOOM                        241
#define IDS_CORRESPONDING_FILE_ERR_DIRNOTEXIST 242
#define IDI_ZOOMDARK                    242
#define IDS_CORRESPONDING_FILE_ERR_FOLDERREQUIREDFIRST 243
#define IDI_EMPTY                       243
#define IDS_CORRESPONDING_FILE_ERR_FOLDERREQUIREDSECOND 244
#define IDI_EDITORCONFIGACTIVE          244
#define IDS_CORRESPONDING_FILE_ERR_FILESEXIST 245
#define IDI_ICON4                       245
#define IDI_EDITORCONFIGINACTIVE        245
#define IDS_CORRESPONDING_FILE_ERR_FILEEXISTS 246
#define IDB_BITMAP1                     246
#define IDB_EMPTYCHECKED                246
#define IDS_FETCHING_PLUGINS_LIST       247
#define IDD_REGEXCAPTUREDLG             247
#define IDS_NO_PLUGINS_AVAILABLE        248
#define IDD_COMMANDPALETTE              248
#define IDS_STATUS_CURPOS               249
#define IDS_STATUS_CURPOSLONG           250
#define IDS_STATUSSELECTIONLONG         251
#define IDS_STATUS_TABSOPENLONG         252
#define IDS_STATUS_TABSOPEN             253
#define IDS_STATUSSELECTIONNONE         254
#define IDS_EXTENSIONTOOLTIP            255
#define IDS_STATUSTTR2L                 256
#define IDS_RUNASADMIN                  257
#define IDS_FOLDTEXT                    258
#define IDS_CUSTOMCOMMANDTITLE          259
#define IDS_IMPORTBPLEX_TITLE           260
#define IDS_IMPORTBPLEX_QUESTION        261
#define IDS_IMPORTBPLEX_IMPORT          262
#define IDS_IMPORTBPLEX_OPEN            263
#define IDS_COMMANDPALETTE_FILTERCUE    264
#define IDS_ADDTOQAT                    265
#define IDC_SEARCHCOMBO                 1000
#define IDC_FINDBTN                     1001
#define IDC_REPLACECOMBO                1002
#define IDC_REPLACEBTN                  1003
#define IDC_REPLACEALLBTN               1004
#define IDC_REPLACEALLINTABSBTN         1005
#define IDC_MATCHWORD                   1007
#define IDC_MATCHCASE                   1008
#define IDC_MATCHREGEX                  1009
#define IDC_UNDERLINECHECK              1009
#define IDC_FUNCTIONS                   1010
#define IDC_SEARCHSUBFOLDERS            1012
#define IDC_SEARCHFILES                 1013
#define IDC_LANGCOMBO                   1014
#define IDC_STYLECOMBO                  1015
#define IDC_SEARCHFOLDERFOLLOWTAB       1015
#define IDC_FG_BTN                      1016
#define IDC_FINDRESULTSACTION           1016
#define IDC_BK_BTN                      1017
#define IDC_FONTCOMBO                   1018
#define IDC_FONTSIZECOMBO               1019
#define IDC_BOLDCHECK                   1020
#define IDC_ITALICCHECK                 1021
#define IDC_EXTENSIONS                  1022
#define IDC_LINE                        1022
#define IDC_WEBSEARCHCMD                1022
#define IDC_DESC                        1022
#define IDC_SUMMARY                     1022
#define IDC_LINEINFO                    1024
#define IDC_VERSIONLABEL                1025
#define IDC_WEBLINK                     1026
#define IDC_UPDATECHECK                 1027
#define IDC_LIST                        1028
#define IDC_CUSTNAME0                   1029
#define IDC_CUSTCMD0                    1030
#define IDC_CUSTNAME1                   1031
#define IDC_CUSTCMD1                    1032
#define IDC_CUSTNAME2                   1033
#define IDC_CUSTCMD2                    1034
#define IDC_CUSTNAME3                   1035
#define IDC_CUSTCMD3                    1036
#define IDC_CUSTNAME4                   1037
#define IDC_CUSTCMD4                    1038
#define IDC_CUSTNAME5                   1039
#define IDC_CUSTCMD5                    1040
#define IDC_CUSTNAME6                   1041
#define IDC_CUSTCMD6                    1042
#define IDC_CUSTNAME7                   1043
#define IDC_CUSTCMD7                    1044
#define IDC_CUSTNAME8                   1045
#define IDC_CUSTCMD8                    1046
#define IDC_CUSTNAME9                   1047
#define IDC_CUSTCMD9                    1048
#define IDC_STATIC0                     1049
#define IDC_STATIC1                     1050
#define IDC_STATIC2                     1051
#define IDC_STATIC3                     1052
#define IDC_STATIC4                     1053
#define IDC_STATIC5                     1054
#define IDC_STATIC6                     1055
#define IDC_STATIC7                     1056
#define IDC_STATIC8                     1057
#define IDC_STATIC9                     1058
#define IDC_STATICWEB                   1059
#define IDC_STATICNAME                  1060
#define IDC_STATICCMDLINE               1061
#define IDC_INFO                        1062
#define IDC_SEARCHINFO                  1064
#define IDC_FINDALL                     1065
#define IDC_FINDALLINTABS               1066
#define IDC_FINDRESULTS                 1067
#define IDC_PLUGINSLIST                 1067
#define IDC_FINDALLINDIR                1068
#define IDC_SETSEARCHFOLDER             1069
#define IDC_R_ANSI                      1070
#define IDC_SEARCHFOLDER                1070
#define IDC_R_UTF8                      1071
#define IDC_SETSEARCHFOLDERTOPARENT     1071
#define IDC_R_UTF8BOM                   1072
#define IDC_FINDFILES                   1073
#define IDC_R_UTF16LE                   1073
#define IDC_R_UTF16BE                   1074
#define IDC_SETSEARCHFOLDERCURRENT      1074
#define IDC_R_UTF32LE                   1075
#define IDC_PLUGINGROUP                 1075
#define IDC_R_UTF16BE2                  1076
#define IDC_R_UTF32BE                   1076
#define IDC_SORTDLG_ORDER               1077
#define IDC_SORTDLG_NUM_CHECK           1078
#define IDC_SORTDLG_CASE_CHECK          1079
#define IDC_FINDPREVIOUS                1080
#define IDC_SEARCHFORLABEL              1081
#define IDC_REPLACEWITHLABEL            1082
#define IDC_SORTORDERLABEL              1083
#define IDC_CFNAME1                     1084
#define IDC_CFNAME2                     1085
#define IDC_CFFOLDER1                   1086
#define IDC_CFFOLDER2                   1087
#define IDC_STATUS                      1088
#define IDC_CFCREATE                    1089
#define IDC_CFSETFOLDER1TOPARENT        1090
#define IDC_CFSETFOLDER2TOPARENT        1091
#define IDC_CFFILENAMELBL               1092
#define IDC_CFFOLDERLBL                 1093
#define IDC_SAVEUTF8                    1094
#define IDC_LOADASUTF8                  1094
#define IDC_CRLF_RADIO                  1095
#define IDC_LF_RADIO                    1096
#define IDC_RADIO3                      1097
#define IDC_CR_RADIO                    1097
#define IDC_REGEXCOMBO                  1098
#define IDC_CAPTURECOMBO                1099
#define IDC_CUSTOM1                     1100
#define IDC_SCINTILLA                   1100
#define IDC_REGEXLABEL                  1101
#define IDC_CAPTURELABEL                1102
#define IDC_INFOLABEL                   1103
#define IDC_ICASE                       1104
#define IDC_CHECK2                      1105
#define IDC_DOTNEWLINE                  1105
#define IDC_REMOVEDUPLICATES            1106
#define IDC_FILTER                      1107
#define IDC_RESULTS                     1110
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        249
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
